SELECT
	MARKET_DISPLAY_NAME
	,MSTR_DIVISION_DESC
	,MSTR_DEPARTMENT_DESC
	,MSTR_POG_DESC
	,MSTR_CLASS_DESC
	,MSTR_BUYER_LAST_FIRST_NAME
	,NIQ_MANUFACTURER_DESC
	,NIQ_BRAND_DESC
	,PL_IND
	,WEEK_END
	,SALES

FROM
(
	SELECT
		MSTR_DIVISION_DESC
		,MSTR_DEPARTMENT_DESC
		,MSTR_POG_DESC
		,MSTR_CLASS_DESC
		,MSTR_BUYER_LAST_FIRST_NAME
		,NIQ_MANUFACTURER_DESC
		,NIQ_BRAND_DESC
		,PL_IND
		,WEEK_END
		,CAST(XAOC AS NUMBER(38,2)) AS XAOC
		,CAST(FOOD AS NUMBER(38,2)) AS FOOD
		,CAST(DRUG AS NUMBER(38,2)) AS DRUG
		,CAST(AOWM AS NUMBER(38,2)) AS AOWM

	FROM
	(
		SELECT
			MSTR_DIVISION_DESC
			,MSTR_DEPARTMENT_DESC
			,MSTR_POG_DESC
			,MSTR_CLASS_DESC
			,MSTR_BUYER_LAST_FIRST_NAME
			,NIQ_MANUFACTURER_DESC
			,NIQ_BRAND_DESC
			,PL_IND
			,WEEK_END
			,XAOC
			,FOOD
			,DRUG
			,(XAOC - FOOD - DRUG) AS AOWM

		FROM
		(
			SELECT
				MSTR_DIVISION_DESC
				,MSTR_DEPARTMENT_DESC
				,MSTR_POG_DESC
				,MSTR_CLASS_DESC
				,MSTR_BUYER_LAST_FIRST_NAME
				,NIQ_MANUFACTURER_DESC
				,NIQ_BRAND_DESC
				,PL_IND
				,WEEK_END
				,CASE
					WHEN XAOC IS NULL
						THEN 0
						ELSE XAOC
					END AS XAOC
				,CASE
					WHEN FOOD IS NULL
						THEN 0
						ELSE FOOD
					END AS FOOD
				,CASE
					WHEN DRUG IS NULL
						THEN 0
						ELSE DRUG
					END AS DRUG

			FROM
			(
				SELECT *

				FROM
				(
					SELECT
						MARKET_DISPLAY_NAME
						,MSTR_DIVISION_DESC
						,MSTR_DEPARTMENT_DESC
						,MSTR_POG_DESC
						,MSTR_CLASS_DESC
						,MSTR_BUYER_LAST_FIRST_NAME
						,NIQ_MANUFACTURER_DESC
						,NIQ_BRAND_DESC
						,PL_IND
						,WEEK_END
						,SALES

					FROM "DOLLARGENERAL"."MARKET_SHARE"."ROM_TOTAL_STORE_TY"
				)

				PIVOT(SUM(SALES) FOR MARKET_DISPLAY_NAME IN ('Dol Gen Total RM xAOC','Dol Gen Total RM Food','Total US Drug')) AS P
				(
					MSTR_DIVISION_DESC
					,MSTR_DEPARTMENT_DESC
					,MSTR_POG_DESC
					,MSTR_CLASS_DESC
					,MSTR_BUYER_LAST_FIRST_NAME
					,NIQ_MANUFACTURER_DESC
					,NIQ_BRAND_DESC
					,PL_IND
					,WEEK_END
					,XAOC
					,FOOD
					,DRUG
				)
			)
		)
	)
)

UNPIVOT(SALES FOR MARKET_DISPLAY_NAME IN (XAOC, FOOD, DRUG, AOWM))